name: Build Windows EXE

on:
  push:
    branches: [ main ]  # Jalankan workflow saat push ke branch 'main'
  workflow_dispatch:     # Bisa juga dijalankan manual via tombol "Run workflow"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Build Windows EXE
        run: flutter build windows

      - name: Check Release Output (Debugging)
        run: dir build\windows\runner\Release

      - name: Upload Windows EXE Artifact
        uses: actions/upload-artifact@v2
        with:
          name: windows-release
          path: build/windows/runner/Release/
